name: Maven publish

on:
  push:
    branches:
      - main

jobs:
  build:
  
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v1
    - name: Setup JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
        server-id: snapshots
        settings-path: ${{github.workspace}}
    - name: clean .m2
      run: rm -rf ~/.m2
    - name: Build and package
      run: |
        mvn -B package --file pom.xml -s settings.xml
    - name: Build with Maven
      run: |
        mvn deploy --file pom.xml -s settings.xml
